export const STATUS_OPTIONS = ['Playing', 'Completed', 'Wishlist']
export const GENRE_OPTIONS = ['Action RPG', 'Adventure', 'JRPG', 'Open World', 'Platformer', 'Roguelike', 'Strategy']
export const STORAGE_KEYS = {
  games: 'gamevault-games',
  theme: 'gamevault-theme',
  locale: 'gamevault-locale',
  palette: 'gamevault-palette',
}

export const COLOR_PALETTES = [
  {
    id: 'violet',
    name: 'Violet Pulse',
    accent: '#8b5cf6',
    accentStrong: '#7c3aed',
    accentMuted: '#c4b5fd',
    darkSurface: '#020617',
    darkPanel: '#111827',
    darkPanelSoft: '#1f2937',
    lightSurface: '#eef2ff',
    lightPanel: '#f8fafc',
    lightPanelSoft: '#eef2ff',
    textLight: '#f8fafc',
    textDark: '#0f172a',
    borderLight: '#cbd5e1',
    borderDark: '#334155',
  },
  {
    id: 'cyan',
    name: 'Cyan Flash',
    accent: '#22d3ee',
    accentStrong: '#06b6d4',
    accentMuted: '#bae6fd',
    darkSurface: '#061119',
    darkPanel: '#0f172a',
    darkPanelSoft: '#1e293b',
    lightSurface: '#ecfeff',
    lightPanel: '#f8fafc',
    lightPanelSoft: '#e0f2fe',
    textLight: '#f8fafc',
    textDark: '#0f172a',
    borderLight: '#bae6fd',
    borderDark: '#334155',
  },
  {
    id: 'amber',
    name: 'Amber Glow',
    accent: '#f59e0b',
    accentStrong: '#d97706',
    accentMuted: '#fde68a',
    darkSurface: '#241b0a',
    darkPanel: '#111827',
    darkPanelSoft: '#212121',
    lightSurface: '#fff7ed',
    lightPanel: '#fef3c7',
    lightPanelSoft: '#fff9db',
    textLight: '#f8fafc',
    textDark: '#111827',
    borderLight: '#fde68a',
    borderDark: '#524b0d',
  },
]
